"""add all

Revision ID: adc7123720a8
Revises: 
Create Date: 2024-07-24 19:39:30.268175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc7123720a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_customers',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.String(length=20), nullable=False),
    sa.Column('end_time', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('organizer', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_openings',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('experience_required', sa.String(length=100), nullable=True),
    sa.Column('education_required', sa.String(length=100), nullable=True),
    sa.Column('salary_range', sa.String(length=50), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('managers',
    sa.Column('manager_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('department', sa.String(length=40), nullable=False),
    sa.Column('joining_date', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('manager_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_managers_name'), 'managers', ['name'], unique=False)
    op.create_table('otp',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_email', sa.String(length=50), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('expiration_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('employees',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('manager_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('position', sa.String(length=30), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('DOB', sa.String(length=15), nullable=False),
    sa.Column('date_hired', sa.DateTime(), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.manager_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_table('attendance',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('check_in_time', sa.DateTime(), nullable=False),
    sa.Column('check_out_time', sa.DateTime(), nullable=True),
    sa.Column('is_present', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_exit',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=False),
    sa.Column('reason_for_exit', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_to', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('notification_id', sa.String(length=50), nullable=False),
    sa.Column('recipient_id', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('project',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('manager_id', sa.String(length=50), nullable=False),
    sa.Column('emp_id', sa.String(length=50), nullable=False),
    sa.Column('Title', sa.String(length=50), nullable=False),
    sa.Column('Desciption', sa.String(length=300), nullable=False),
    sa.Column('start_date', sa.String(length=50), nullable=True),
    sa.Column('end_date', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.manager_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_Desciption'), 'project', ['Desciption'], unique=False)
    op.create_index(op.f('ix_project_Title'), 'project', ['Title'], unique=False)
    op.create_index(op.f('ix_project_status'), 'project', ['status'], unique=False)
    op.create_table('time_tracking',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('emp_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('check_in_time', sa.String(length=20), nullable=False),
    sa.Column('check_out_time', sa.String(length=20), nullable=True),
    sa.Column('hours_worked', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('extra_hours', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('emp_id', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('time_tracking')
    op.drop_index(op.f('ix_project_status'), table_name='project')
    op.drop_index(op.f('ix_project_Title'), table_name='project')
    op.drop_index(op.f('ix_project_Desciption'), table_name='project')
    op.drop_table('project')
    op.drop_table('notification')
    op.drop_table('equipment')
    op.drop_table('employee_exit')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('otp')
    op.drop_index(op.f('ix_managers_name'), table_name='managers')
    op.drop_table('managers')
    op.drop_table('job_openings')
    op.drop_table('events')
    op.drop_table('crm_customers')
    # ### end Alembic commands ###
